select * from BRONZE_SBA_LOANS;

-- update dates from varchar to standard date format
update BRONZE_SBA_LOANS
set record_date = to_date(record_date,'mm/dd/yyyy'),
approval_date = to_date(approval_date,'mm/dd/yyyy'),
firstdisbursement_date = to_date(firstdisbursement_date,'mm/dd/yyyy'),
paidfull_date = to_date(paidfull_date,'mm/dd/yyyy');

-- clean currency column
UPDATE BRONZE_SBA_LOANS
SET thirdparty_amount = REGEXP_REPLACE(thirdparty_amount, '[^0-9]', ''),
gross_approval = REGEXP_REPLACE(gross_approval, '[^0-9]', '');

-- table metadata
DESCRIBE TABLE BRONZE_SBA_LOANS;

-- discard any records where gross approval is 0 or null
select * from BRONZE_SBA_LOANS where gross_approval is null;


-- find rows with exact same values across columns
SELECT *,
       COUNT(*) AS duplicate_count
FROM BRONZE_SBA_LOANS
GROUP BY ALL
HAVING COUNT(*) > 1
order by borrower_name desc;

-- delete duplicate records
CREATE OR REPLACE TABLE BRONZE_SBA_LOANS AS
SELECT DISTINCT *
FROM BRONZE_SBA_LOANS;

-- add auto INCREMENT index
ALTER TABLE BRONZE_SBA_LOANS
ADD COLUMN ID INT AUTOINCREMENT;


SELECT * from BRONZE_SBA_LOANS
WHERE loan_term_months = 0 ;
  
-- add column to review silver layer changes timestamp
ALTER TABLE bronze_sba_loans ADD COLUMN silver_layer_processed TIMESTAMP_NTZ;

-- add current timestamp to silver layer process
update bronze_sba_loans
set silver_layer_processed = CURRENT_TIMESTAMP;

select * from bronze_sba_loans 
where loan_status is null;


-- to show total no of loan for each status
select loan_status, count(*) as Loan_status 
from bronze_sba_loans
group by loan_status;

--average jobs generated by businesses
select avg(jobs_supported) from bronze_sba_loans;

-- average loan ammount applied for
select '$' || avg(gross_approval) as Average_gross_apporval from bronze_sba_loans;

-- the states with total loans applied 
select borr_state, count(*) as total_loans_applied
from bronze_sba_loans
group by borr_state;

-- state with min loans applied
select borr_state, count(*) as total_loans_applied
from bronze_sba_loans
group by borr_state
order by total_loans_applied asc
limit 1;

--state with max loans applied
select borr_state, count(*) as total_loans_applied
from bronze_sba_loans
group by borr_state
order by total_loans_applied desc
limit 1;

-- total loan approved every year
select approval_fiscal_year,
       count(*) as Total_loan_approved
from bronze_sba_loans
group by approval_fiscal_year
order by approval_fiscal_year asc;

--min loan approved in a year
select approval_fiscal_year,
       count(*) as Total_loan_approved
from bronze_sba_loans
group by approval_fiscal_year
order by Total_loan_approved asc
limit 2;

--min loan approved in a year
select approval_fiscal_year,
       count(*) as Total_loan_approved
from bronze_sba_loans
group by approval_fiscal_year
order by Total_loan_approved desc
limit 1;

-- count of loans by business type
select business_type, count(*) as total_loans 
from bronze_sba_loans
group by business_type
order by total_loans desc;

-- total loans paid in full
select count(paidfull_date)
from bronze_sba_loans
where paidfull_date is not null;

-- table after silver layer processed
CREATE OR REPLACE TABLE silver_sba_loans AS
SELECT 
    record_date,
    lender_id,
    borrower_name,
    borr_state,
    cdc_name,
    cdc_state,
    thirdpartylender_name,
    thirdpartylender_state,
    thirdparty_amount,
    gross_approval,
    approval_date,
    approval_fiscal_year,
    firstdisbursement_date,
    business_type,
    business_age,
    loan_status,
    paidfull_date,
    jobs_supported,
    collateral,
    loan_term_years,
    silver_layer_processed
FROM bronze_sba_loans
WHERE loan_term_months > 0; -- Example of "Heavy Filtering"


select * from silver_sba_loans;


------- GIT INTEGRATION
CREATE OR REPLACE SECRET git_hub_token
  TYPE = PASSWORD
  USERNAME = 'rutvipatel122'
  PASSWORD = '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';

CREATE OR REPLACE API INTEGRATION git_api_int
  API_ALLOWED_PREFIXES = ('https://github.com/rutvipatel122/')
  API_PROVIDER = git_https_api
  ENABLED = TRUE;

ALTER API INTEGRATION git_api_int 
SET ALLOWED_AUTHENTICATION_SECRETS = ('PROJECT.ANALYSIS.GIT_HUB_TOKEN');

CREATE OR REPLACE GIT REPOSITORY loan_project_scripts
  API_INTEGRATION = git_api_int
  GIT_CREDENTIALS = git_hub_token
  ORIGIN = 'https://github.com/rutvipatel122/DE_project';